#!/bin/bash

### SYSTEM

_echot "------- grub"
file=/etc/default/grub
_keepcp ${file}
sudo sed -i "s|^.\?\(GRUB_TIMEOUT_STYLE\)=.*|\1=menu|" ${file}
sudo sed -i "/^GRUB_TIMEOUT=/ s|=.*|=2|" ${file}
sudo sed -i "/^GRUB_DEFAULT=/ s|=.*|=0|" ${file}
sudo sed -i "/^GRUB_SAVEDEFAULT=/ s|=.*|=false|" ${file} # manjaro
file=/etc/grub.d/00_header
_keepcp ${file}
sudo sed -i "s|30|2|g" ${file}
_evalr update-grub

_echot "------- reduce swapiness"
sudo swapoff -av
sudo sh -c 'echo vm.swappiness=40 > /etc/sysctl.d/99-swappiness.conf' # limit swap
sudo swapon -v

_echot "------- UTC 0"
sudo rm /etc/localtime && sudo ln -sv /usr/share/zoneinfo/Etc/UTC /etc/localtime

_echot "------- profile"
sudo sh -c "echo '# QT
export QT_QPA_PLATFORMTHEME=qt5ct' > /etc/profile.d/desktop.sh"

_echot "------- bash-completion"
_evalr "cp -a ${_PATH_BASE}/xtra/bash-completion/* /usr/share/bash-completion/completions/"

_echot "------- vim links edit"
for file in /usr/bin/edit /usr/bin/editor; do
	[ -e ${file} ] && _evalr rm ${file}
	_evalr ln -sv /usr/bin/vim ${file}
done

_echot "------- vim colors"
_evalr cp ${_PATH_BASE}/conf/vim/* /usr/share/vim/vim*/colors/

_echot "------- vim conf"
file=/etc/vim/vimrc
sudo sed -i "s|^\"\(syntax\).*|\1 on|" ${file}
opts="background=dark showmatch"
# uncomment
for opt in ${opts}; do
	sudo sed -i "s|^\"\(set ${opt}.*\)$|\1|" ${file}
done

_echot "------- meld style"
_evalr cp ${_PATH_BASE}/conf/meld-dark.xml /usr/share/meld/styles/

_echot "------- icons"
path=/usr/share/icons/Foralyse
[ -d "${path}" ] || sudo mkdir -p ${path}
_evalr cp ${_PATH_BASE}/icons/* ${path}/

_echot "------- wp"
path=/usr/share/xfce4/backdrops
_evalr cp ${_PATH_BASE}/xtra/wp/* ${path}/
_evalr chmod 644 ${path}/*

### USER

_echot "------- thunar-volman"
xfconf-query -c thunar-volman -p /autobrowse/enabled -s false
xfconf-query -c thunar-volman -p /automount-drives/enabled -s false
xfconf-query -c thunar-volman -p /automount-media/enabled -s false

_echot "------- user conf"
for file in .nanorc .tmux.conf .vimrc; do
	path=${HOME}/${file}
	_keepmv "${path}"
	_eval cp "${_PATH_REPO_BS}/conf/${file}" "${path}"
done

_echot "------- gtk styles"
path=${HOME}/.local/share/gtksourceview-3.0/styles
[ -d "${path}" ] || mkdir -p ${path}
_eval cp ${_PATH_BASE}/conf/styles/* ${path}/
# gtk 4
cd ${HOME}/.local/share
path=gtksourceview-4
[ -e "${path}" ] || ln -sv gtksourceview-3.0 ${path}

_echot "------- user conf"
paths=".tmux .wxHexEditor .java/.userPrefs/us/deathmarine/luyten/"
for path in ${paths}; do
	_keepmv ${path}
done
for file in $(ls ${_PATH_BASE}/conf/user.*.tar.gz); do
	tar xzf ${file} -C ${HOME}/
done

_echot "------- nano"
for str in conf install; do
	_evalr cp -a /usr/share/nano/sh.nanorc /usr/share/nano/${str}.nanorc
	sudo sed -i 's|^\(syntax \).*|\1"'${str}'" "\.'${str}'$"|' /usr/share/nano/${str}.nanorc
done
file=/etc/nanorc
_keepcp ${file}
sudo sed -i 's|^.*\(set tabsize\).*|\1 4|' ${file}
sudo sed -i 's|^\(set cut.*\)$|# \1|' ${file}
sudo sed -i 's|^\(set linenumbers.*\)$|# \1|' ${file}
sudo sed -i '/^# *include/ s/^# //' ${file}
# uncomment
opts="constantshow historylog matchbrackets multibuffer nohelp softwrap " # various
opts+="errorcolor functioncolor keycolor numbercolor selectedcolor statuscolor stripecolor titlecolor" # color
for opt in ${opts}; do
	sudo sed -i "s|^.*\(set $opt .*\)$|\1|"  ${file}
done

_echot "------- geany"
path=${HOME}/.config/geany/colorschemes
_keepmv ${path}
[ -d "${path}" ] || mkdir -p ${path}
 cp ${_PATH_BASE}/conf/geany/* ${path}/

_echot "------- bless"
path=${HOME}/.config/bless/layouts/
_keepmv ${path}
[ -d "${path}" ] || mkdir -p ${path}
cp ${_PATH_BASE}/conf/bless/* ${path}/

_echot "------- tmux desktop"
cp ${_PATH_BASE}/xtra/xfce4-terminal-tmux.desktop ${HOME}/.local/share/applications/

_echot "------- user icons"
path=${HOME}/.local/share/icons
cp ${_PATH_BASE}/icons/* ${path}/

_echot "------- 56xubuntu-session"
file=/etc/X11/Xsession.d/56xubuntu-session
[ -f "${file}" ] && sudo sed -i '/export QT_QPA_PLATFORMTHEME=/ s|=.*$|=qt5ct|' ${file}

_echot "------- profile"
export QT_QPA_PLATFORMTHEME=qt5ct # gtk2
echo -e "\n# QT\nexport QT_QPA_PLATFORMTHEME=qt5ct " >> ${HOME}/.profile
echo -e "\n#JAVA\nexport _JAVA_OPTIONS=\"-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel -Dswing.crossplatformlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel \${_JAVA_OPTIONS}\"" >> ${HOME}/.profile

_echot "------- QT5"
_echoA "After validation, adjust settings for qt5 and close qt5ct window"
_askno "Validate to continue"
qt5ct 2>/dev/null

_echot "------- plank"
path=${HOME}/.config/autostart
[ -d "${path}" ] || mkdir -p ${path}
cp ${_PATH_BASE}/xtra/plank.desktop ${path}/
_echoA "After validation, adjust plank preferences and close plank window"
_askno "Validate to continue"
plank --preferences &
