#!/bin/bash

### global

packages="libc6:i386 libexpat1:i386 libffi7:i386 libfontconfig1:i386 libfreetype6:i386 libgcc-s1:i386"
packages+=" libglib2.0-0:i386 libice6:i386 libpcre3:i386 libpng16-16:i386 libsm6:i386 libstdc++6:i386"
packages+=" libuuid1:i386 libx11-6:i386 libxau6:i386 libxcb1:i386 libxdmcp6:i386 libxext6:i386 libxrender1:i386"
packages+=" zlib1g:i386 libx11-xcb1:i386 libdbus-1-3 libxi6:i386 libsm6:i386 libcurl4:i386"
# libdbus-1-3:i386
${_CMD_INS} ${packages}

${_CMD_INS} libgtk2.0-0 gtk2-engines-murrine:i386 gtk2-engines-pixbuf:i386 libpango1.0-0:i386
# libgtk2.0-0:i386

### IDA

file_soft=$( ls ${_PATH_SHARE}/trans/idafree*_linux.run )
if [ -z "${file_soft}" ]; then
	_echoA "Download IDA free version from hex-rays.com \nand put the file idafree*_linux.run in shared path: ${_PATH_SHARE}"
	_askno "Validate to continue"
	file_soft=$( ls ${_PATH_SHARE}/trans/idafree*_linux.run )
	[ -z "${file_soft}" ] && _exite "Unable to find file: ${file_soft}"
fi

path=/opt/idafree
sudo mkdir ${path}
sudo chown ${USER}:${USER} ${path}
_echoA "After validation, give this path for installation: ${path}"
_askno "Validate to continue"
sudo chmod +x ${file_soft}
${file_soft}

sudo ln -sv ${path}/ida64 /usr/local/bin/idafree 
file=~/.local/share/applications/
[ -f "${file}" ] && rm ${file}
cp ${_PATH_BASE}/xtra/idafree.desktop  ~/.local/share/applications/

