#!/bin/bash

###  install

${_CMD_INS} qemu-utils

###  conf

# paths
paths="${_PATH_NBD} ${HOME}/.config/gtk-3.0"
for path in ${paths}; do
	[ -d "${path}" ] || _evalr mkdir -p ${path}
done

# script
file=${_PATH_REPO_BS}/scripts/nbd.sh
file2=/usr/local/bin/nbd
! [ -f "${file}" ] && _exite "Unable to find file: ${file}"
_evalr cp ${file} ${file2}
_evalr chmod +x ${file2}
sudo sed -i "/^_PATH_NBD=/ s|=.*$|=${_PATH_NBD}|" ${file2}

# bookmarks
file=${HOME}/.config/gtk-3.0/bookmarks
grep -q "file://${_PATH_NBD}" ${file} || echo "file://${_PATH_NBD}" >> ${file}

###  Thunar custom actions

file=${HOME}/.config/Thunar/uca.xml
[ -d "${HOME}/.config/Thunar" ] || mkdir -p ~/.config/Thunar
if [ -f "${file}" ]; then
	[ -f ${file}.keep ] || cp -a ${file} ${file}.keep
else
	echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<actions>\n</actions>' > ${file}
fi
# not already made
if ! grep -q 1655620394868230-1 ${file}; then
	sed -i '$,1d' ${file}
	cat ${file} ${_PATH_BASE}/conf/ca.xml > ${file}.tmp
	_eval mv ${file}.tmp ${file}
fi

_echoA "logout/login from your computer to apply changes"
