#!/bin/bash

_echot "------- .bash_aliases"
file=/root/.bash_aliases
_keepmv ${file}
_evalr cp ${_PATH_REPO_BS}/conf/.bash_aliases ${file}

_echot "------- .bashrc"
file="/root/.bashrc"
_keepcp ${file}

# force color
sudo sed -i '/^#force_color_prompt=/ s|#||' ${file}
# PS1
color='\\[\\033[01;31m\\]' # '\\[\\033[01;34m\\]'
sudo sed -i 's|^\(\s*PS1=\).*00m.*$|\1"\${debian_chroot:+(\$debian_chroot)}'${color}'\\h\\[\\033[00m\\] \\W'${color}'#\\[\\033[00m\\] "|' ${file}
sudo sed -i "/^\s*PS1=.*00m/ s|\"|'|g" ${file}

# aliases
sudo grep -q "/.bash_aliases" ${file} || sudo sh -c "echo '
# bash_aliases
[ -f /root/.bash_aliases ] && . /root/.bash_aliases
'  >> ${file}"

_echot "------- .vimrc"
file=/root/.vimrc
_keepmv ${file}
_evalr cp ${_PATH_REPO_BS}/conf/.vimrc ${file}
