#!/bin/bash

### volatility3

python3 -m pip install -U pefile yara-python capstone pycryptodome jsonschema leechcorepyc python-snappy

python3 -m pip install -U volatility3
cd ~/.local/bin && ln -sv vol vol3

_echoa vol3
vol3 -h
_askno "Validate to continue"

### volatility2

# https://github.com/volatilityfoundation/volatility/wiki/Installation

##### global

${_CMD_INS} pcregrep libpcre++-dev python2-dev

python2 -m pip install distorm3 ipython openpyxl pycrypto pytz ujson yara-python

##### libforensic1394

${_CMD_INS} cmake

cd /tmp
git clone https://github.com/FreddieWitherden/libforensic1394
cd libforensic1394
mkdir build && cd build
cmake -G"Unix Makefiles" ../
sudo make install
cd ../python
sudo python2 setup.py install

cd
sudo rm -fR /tmp/libforensic1394
${_CMD} remove -y cmake
${_CMD} -y autoremove

##### volatility

cd /opt
sudo git clone https://github.com/volatilityfoundation/volatility.git
cd volatility
sudo rm -fR .git
sudo python2 setup.py install

cd /usr/local/bin
sudo ln -sv vol.py vol2

_echoa vol2
vol2 -h

