#!/bin/bash

###  install

${_CMD_INS} qemu-utils

###  conf

# paths
paths="${_PATH_NBD}"
for path in ${paths}; do
	[ -d "${path}" ] || sudo mkdir -p ${path}
done

# script
file=${_PATH_BASE}/xtra/nbd.sh
file2=/usr/local/bin/${file##*/}
! [ -f "${file}" ] && _exite "Unable to find file: ${file}"
sudo cp ${file} ${file2}
sudo chmod +x ${file2}
sudo sed -i "/^_PATH_NBD=/ s|=.*$|=${_PATH_NBD}|" ${file2}

###  Thunar custom actions

file=~/.config/Thunar/uca.xml
[ -d ~/.config/Thunar ] || mkdir -p ~/.config/Thunar
if [ -f "${file}" ]; then
	[ -f ${file}.keep ] || cp -a ${file} ${file}.keep
else
	echo -e '<?xml version="1.0" encoding="UTF-8"?>\n<actions>\n</actions>' > ${file}
fi

# update already made
grep -q 1655620394868230-1 ${file} && return

sed -i '$,1d' ${file}
cat ${file} ${_PATH_BASE}/conf/ca.xml > ${file}.tmp
mv ${file}.tmp ${file}

_echoA "logout/login from your computer to apply changes"
